/*
 * Dialogo.java
 *
 * Created on 23 de septiembre de 2008, 19:57
 */

package com.fsaravia.utilities;

import javax.swing.JOptionPane;

/**
 *
 * @author  Federico Saravia
 */
public class Dialogo extends javax.swing.JDialog {

    /** Creates new form Dialogo */
    public Dialogo(javax.swing.JFrame parent, boolean modal,String titulo,String mensaje) {
        super(parent, modal);
        initComponents();
        this.setTitle(titulo);
        jOptionPane1.setMessage(mensaje);
        jOptionPane1.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        jOptionPane1.setOptions(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());
        getContentPane().add(jOptionPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables

}
